server:
  port: 8081
spring:
  profiles:
    active: druid
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  # redis 配置
  redis:
    # 地址
#    host: 192.168.188.99
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

mybatis-plus:
  type-aliases-package: com.zhang.web.entity

# 日志配置
logging:
  level:
    com.zhang: debug
    org.springframework: warn
